// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transport.Infrastructure.Database;

#nullable disable

namespace Transport.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TransportContext))]
    [Migration("20260425131622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Transport.Domain.Entities.Transport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<byte>("MaxPassengersCount")
                        .HasColumnType("smallint")
                        .HasColumnName("max_passengers_count");

                    b.Property<string>("NumberPlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("number_plate");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_transport");

                    b.HasIndex("NumberPlate")
                        .IsUnique()
                        .HasDatabaseName("ix_transport_number_plate");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_transport_type_id");

                    b.ToTable("transport", (string)null);
                });

            modelBuilder.Entity("Transport.Domain.Entities.TransportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_transport_type");

                    b.ToTable("transport_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Самолет"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Вертолет"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Автобус"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Микроавтобус"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Легковой автомобиль"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Минивэн"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Внедорожник"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Грузовик"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Поезд"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Катер"
                        });
                });

            modelBuilder.Entity("Transport.Domain.Entities.Transport", b =>
                {
                    b.HasOne("Transport.Domain.Entities.TransportType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transport_transport_type_type_id");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
